export const CORPORATE_JARGON_WEIGHTS = {
  leverage: 8,
  synergy: 12,
  synergies: 12,
  alignment: 10,
  stakeholder: 10,
  stakeholders: 10,
  "cross-functional": 12,
  strategic: 10,
  optimization: 12,
  optimize: 8,
  streamline: 10,
  efficiency: 8,
  scalable: 8,
  growth: 6,
  initiative: 8,
  transformation: 14,
  "operational excellence": 18,
  "north star": 16,
  "low-hanging fruit": 14,
  "circle back": 14,
  "move the needle": 16,
  "above my paygrade": 20,
  "action item": 8,
  "back burner": 12,
  bandwidth: 14,
  "brain dump": 10,
  "break down silos": 18,
  "bring it to the table": 12,
  "buy-in": 12,
  churn: 8,
  "core competencies": 14,
  "deep dive": 10,
  deliverable: 8,
  deliverables: 8,
  "drill down": 10,
  "ducks in a row": 16,
  "fire drill": 18,
  "flesh out": 8,
  "go to market": 10,
  "hard stop": 8,
  "in the weeds": 12,
  "let's take this offline": 20,
  "one-on-one": 6,
  "pain point": 10,
  ping: 6,
  pivot: 12,
  punt: 14,
  "run the numbers": 8,
  wheelhouse: 10,
  "touch base": 12,
  "slide deck": 8,
} as const;

export const CORPORATE_JARGON = Object.keys(CORPORATE_JARGON_WEIGHTS);