export const CORPORATE_JARGON = [
  "leverage",
  "synergy",
  "synergies",
  "alignment",
  "stakeholder",
  "stakeholders",
  "cross-functional",
  "strategic",
  "optimization",
  "optimize",
  "streamline",
  "efficiency",
  "scalable",
  "growth",
  "initiative",
  "transformation",
  "operational excellence",
  "north star",
  "low-hanging fruit",
  "circle back",
  "move the needle",
  "above my paygrade",
  "action item",
  "back burner",
  "bandwidth",
  "brain dump",
  "break down silos",
  "bring it to the table",
  "buy-in",
  "churn",
  "core competencies",
  "deep dive",
  "deliverable",
  "drill down",
  "ducks in a row",
  "fire drill",
  "flesh out",
  "go to market",
  "hard stop",
  "in the weeds",
  "let's take this offline",
  "one-on-one",
  "pain point",
  "ping",
  "pivot",
  "punt",
  "run the numbers",
  "wheelhouse",
  "touch base",
  "slide deck",
  "deliverables",
];